# name: Build Docker Image

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: read
#   packages: write

# jobs:
#   Build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout source code
#       - name: Checkout code
#         uses: actions/checkout@v4ls

#       # Step 2: Build Docker image
#       - name: Build Docker image
#         run: |
#           docker build -t flask-app .
